# Generated by Django 4.2.1 on 2024-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
