# Generated by Django 4.2.1 on 2024-04-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_card_cardslist_delete_productcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='inventory_system.card'),
        ),
    ]
