# Generated by Django 4.2.1 on 2024-05-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0004_card_photo_cardslist_time_create_alter_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
