# Generated by Django 4.2.1 on 2024-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0006_card_note_alter_card_name_alter_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='note',
            field=models.CharField(blank=True, default='', max_length=510, verbose_name='Заметка:'),
        ),
    ]
