# Generated by Django 4.2.1 on 2024-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0007_alter_card_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
